# Generated by Django 2.2.9 on 2020-01-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
