# Generated by Django 3.0.4 on 2020-03-17 08:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0025_auto_20200317_0820'),
        ('moderation', '0004_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='summary',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('handled_date', models.DateTimeField(null=True)),
                ('type', models.CharField(choices=[('signup', 'Sign-up')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('refused', 'Refused'), ('approved', 'approved')], default='pending', max_length=40)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='federation.Actor')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='federation.Actor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
