# Generated by Django 2.0 on 2017-12-26 13:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("users", "0002_auto_20171214_2205")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="secret_key",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
