# Generated by Django 2.0.4 on 2018-05-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0005_user_subsonic_api_token")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="permission_federation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="permission_library",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="permission_settings",
            field=models.BooleanField(default=False),
        ),
    ]
