# Generated by Django 2.0.7 on 2018-08-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0011_auto_20180721_1317")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="upload_quota",
            field=models.PositiveIntegerField(blank=True, null=True),
        )
    ]
