# Generated by Django 2.0.9 on 2018-12-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_upload_quota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permission_federation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permission_upload',
        ),
        migrations.AddField(
            model_name='user',
            name='permission_moderation',
            field=models.BooleanField(default=False, help_text='Block/mute/remove domains, users and content', verbose_name='Moderation'),
        ),
    ]
