# Generated by Django 2.1.7 on 2019-03-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_oauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='scope',
            field=models.TextField(blank=True),
        ),
    ]
