# Generated by Django 2.0.3 on 2018-03-19 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("playlists", "0002_auto_20180316_2217")]

    operations = [
        migrations.AlterModelOptions(
            name="playlisttrack", options={"ordering": ("-playlist", "index")}
        ),
        migrations.AddField(
            model_name="playlisttrack",
            name="creation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="playlisttrack",
            name="index",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.RemoveField(model_name="playlisttrack", name="lft"),
        migrations.RemoveField(model_name="playlisttrack", name="position"),
        migrations.RemoveField(model_name="playlisttrack", name="previous"),
        migrations.RemoveField(model_name="playlisttrack", name="rght"),
        migrations.RemoveField(model_name="playlisttrack", name="tree_id"),
        migrations.AlterUniqueTogether(
            name="playlisttrack", unique_together={("playlist", "index")}
        ),
    ]
