# Generated by Django 2.0.3 on 2018-03-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("playlists", "0003_auto_20180319_1214")]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="modification_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="playlisttrack",
            name="index",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(name="playlisttrack", unique_together=set()),
    ]
