// require('fomantic-ui-css/components/accordion.min.js')
require('fomantic-ui-css/components/api.min.js')
require('fomantic-ui-css/components/checkbox.min.js')
// require('fomantic-ui-css/components/colorize.min.js')
require('fomantic-ui-css/components/dimmer.min.js')
require('fomantic-ui-css/components/dropdown.min.js')
// require('fomantic-ui-css/components/embed.min.js')
// require('fomantic-ui-css/components/form.min.js')
require('fomantic-ui-css/components/modal.min.js')
// require('fomantic-ui-css/components/nag.min.js')
// require('fomantic-ui-css/components/popup.min.js')
require('fomantic-ui-css/components/progress.min.js')
// require('fomantic-ui-css/components/rating.min.js')
require('fomantic-ui-css/components/search.min.js')
// require('fomantic-ui-css/components/shape.min.js')
// require('fomantic-ui-css/components/sidebar.min.js')
require('fomantic-ui-css/components/site.min.js')
require('fomantic-ui-css/components/state.min.js')
require('fomantic-ui-css/components/sticky.min.js')
// require('fomantic-ui-css/components/tab.min.js')
require('fomantic-ui-css/components/toast.min.js')
require('fomantic-ui-css/components/transition.min.js')
// require('fomantic-ui-css/components/video.min.js')
require('fomantic-ui-css/components/visibility.min.js')
// require('fomantic-ui-css/components/visit.min.js')
