# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("music", "0012_auto_20161122_1905")]

    operations = [
        migrations.AlterModelOptions(name="importjob", options={"ordering": ("id",)}),
        migrations.AlterModelOptions(
            name="track", options={"ordering": ["album", "position"]}
        ),
        migrations.AddField(
            model_name="album",
            name="release_group_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
