# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("music", "0013_auto_20171213_2211")]

    operations = [
        migrations.AddField(
            model_name="importjob",
            name="track_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="music.TrackFile",
            ),
        )
    ]
