# Generated by Django 2.0.3 on 2018-04-05 18:30

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0005_actor_followers'),
        ('music', '0022_importbatch_import_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='federation_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='federation.Actor'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='federation_source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importjob',
            name='federation_source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importjob',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='source',
            field=models.CharField(choices=[('api', 'api'), ('shell', 'shell'), ('federation', 'federation')], default='api', max_length=30),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imports', to=settings.AUTH_USER_MODEL),
        ),
    ]
