# Generated by Django 2.0.3 on 2018-04-07 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("federation", "0003_auto_20180407_1010"),
        ("music", "0022_importbatch_import_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="uuid",
            field=models.UUIDField(db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="uuid",
            field=models.UUIDField(db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="uuid",
            field=models.UUIDField(db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="importjob",
            name="library_track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="import_jobs",
                to="federation.LibraryTrack",
            ),
        ),
        migrations.AddField(
            model_name="importjob",
            name="uuid",
            field=models.UUIDField(db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="lyrics",
            name="uuid",
            field=models.UUIDField(db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="track",
            name="uuid",
            field=models.UUIDField(db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="trackfile",
            name="creation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="trackfile",
            name="library_track",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="local_track_file",
                to="federation.LibraryTrack",
            ),
        ),
        migrations.AddField(
            model_name="trackfile",
            name="modification_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="trackfile",
            name="uuid",
            field=models.UUIDField(db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="work",
            name="uuid",
            field=models.UUIDField(db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="importbatch",
            name="source",
            field=models.CharField(
                choices=[
                    ("api", "api"),
                    ("shell", "shell"),
                    ("federation", "federation"),
                ],
                default="api",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="importbatch",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
