# Generated by Django 2.0.8 on 2018-09-21 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("music", "0031_auto_20180914_2007")]

    operations = [
        migrations.RenameModel("TrackFile", "Upload"),
        migrations.RenameField(
            model_name="importjob", old_name="track_file", new_name="upload"
        ),
        migrations.RenameField(
            model_name="library", old_name="files_count", new_name="uploads_count"
        ),
        migrations.AlterField(
            model_name="upload",
            name="library",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploads",
                to="music.Library",
            ),
        ),
        migrations.AlterField(
            model_name="upload",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploads",
                to="music.Track",
            ),
        ),
    ]
