# Generated by Django 2.0.9 on 2018-11-27 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0033_auto_20181023_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('copyleft', models.BooleanField()),
                ('commercial', models.BooleanField()),
                ('attribution', models.BooleanField()),
                ('derivative', models.BooleanField()),
                ('redistribute', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='uploadversion',
            name='mimetype',
            field=models.CharField(choices=[('audio/ogg', 'ogg'), ('audio/mpeg', 'mp3'), ('audio/x-flac', 'flac'), ('audio/flac', 'flac')], max_length=50),
        ),
        migrations.AddField(
            model_name='track',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='music.License'),
        ),
    ]
