# Generated by Django 2.0.9 on 2018-12-03 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0034_auto_20181127_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='copyright',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracks', to='music.License'),
        ),
    ]
