# Generated by Django 2.0.9 on 2018-12-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0035_auto_20181203_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='disc_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
