# Generated by Django 2.0.9 on 2019-01-03 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0036_track_disc_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['album', 'disc_number', 'position']},
        ),
        migrations.AlterField(
            model_name='album',
            name='creation_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='artist',
            name='creation_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='track',
            name='creation_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='upload',
            name='creation_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='work',
            name='creation_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
