# Generated by Django 2.1.7 on 2019-04-09 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("federation", "0017_auto_20190130_0926"),
        ("music", "0037_auto_20190103_1757"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="attributed_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attributed_artists",
                to="federation.Actor",
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="attributed_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attributed_albums",
                to="federation.Actor",
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="attributed_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attributed_tracks",
                to="federation.Actor",
            ),
        ),
    ]
