# Generated by Django 2.1.7 on 2019-04-23 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0038_attributed_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyrics',
            name='work',
        ),
        migrations.RemoveField(
            model_name='work',
            name='from_activity',
        ),
        migrations.RemoveField(
            model_name='track',
            name='work',
        ),
        migrations.DeleteModel(
            name='Lyrics',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
