# Generated by Django 2.2.5 on 2019-10-21 13:18

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import funkwhale_api.music.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0039_auto_20190423_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackActor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('internal', models.BooleanField(db_index=True, default=False)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_actor_items', to='music.Track')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_actor_items', to='music.Upload')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='track_actor_items', to='federation.Actor')),
            ],
            options={
                'unique_together': {('track', 'actor', 'internal', 'upload')},
            },
        ),
    ]
