# Generated by Django 2.2.6 on 2019-11-12 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20191111_1338'),
        ('music', '0041_auto_20191021_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='attachment_cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Attachment', blank=True),
        ),
    ]
