# Generated by Django 2.2.7 on 2020-01-13 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_content'),
        ('music', '0045_full_text_search_stop_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Content'),
        ),
        migrations.AddField(
            model_name='artist',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Content'),
        ),
        migrations.AddField(
            model_name='track',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Content'),
        ),
    ]
