# Generated by Django 2.2.9 on 2020-01-16 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_content'),
        ('music', '0046_auto_20200113_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='attachment_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_artist', to='common.Attachment'),
        ),
        migrations.AddField(
            model_name='track',
            name='attachment_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_track', to='common.Attachment'),
        ),
        migrations.AlterField(
            model_name='album',
            name='attachment_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_album', to='common.Attachment'),
        ),
    ]
