# Generated by Django 2.2.9 on 2020-01-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0048_auto_20200120_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='content_category',
            field=models.CharField(choices=[('music', 'music'), ('podcast', 'podcast'), ('other', 'other')], db_index=True, default='music', max_length=30, null=True),
        ),
    ]
