# Generated by Django 2.2.9 on 2020-01-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0049_auto_20200122_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='mbid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
