# Generated by Django 2.0.3 on 2018-04-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("federation", "0001_initial")]

    operations = [
        migrations.AlterUniqueTogether(
            name="actor", unique_together={("domain", "preferred_username")}
        )
    ]
