# Generated by Django 2.0.3 on 2018-04-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0003_auto_20180407_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrequest',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='followrequest',
            name='target',
        ),
        migrations.AddField(
            model_name='follow',
            name='approved',
            field=models.NullBooleanField(default=None),
        ),
        migrations.DeleteModel(
            name='FollowRequest',
        ),
    ]
