# Generated by Django 2.0.3 on 2018-04-13 17:23

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import funkwhale_api.federation.models


class Migration(migrations.Migration):

    dependencies = [("federation", "0004_auto_20180410_2025")]

    operations = [
        migrations.AddField(
            model_name="librarytrack",
            name="audio_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=funkwhale_api.federation.models.get_file_path,
            ),
        ),
        migrations.AlterField(
            model_name="librarytrack",
            name="metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default={},
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                max_length=10000,
            ),
        ),
    ]
