# Generated by Django 2.0.3 on 2018-04-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0004_followrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='followers',
            field=models.ManyToManyField(related_name='following', through='federation.Follow', to='federation.Actor'),
        ),
    ]
