# Generated by Django 2.0.7 on 2018-08-07 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0029_auto_20180807_1748"),
        ("federation", "0007_auto_20180807_1748"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryfollow",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_follows",
                to="music.Library",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="federation.Actor",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="libraryfollow", unique_together={("actor", "target")}
        ),
    ]
