# Generated by Django 2.0.8 on 2018-08-22 19:56

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import funkwhale_api.federation.models


class Migration(migrations.Migration):

    dependencies = [("federation", "0008_auto_20180807_1748")]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inbox_activities",
                to="federation.Actor",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="payload",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=funkwhale_api.federation.models.empty_dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                max_length=50000,
            ),
        ),
        migrations.AlterField(
            model_name="librarytrack",
            name="metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=funkwhale_api.federation.models.empty_dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                max_length=10000,
            ),
        ),
    ]
