# Generated by Django 2.0.8 on 2018-09-10 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('federation', '0010_auto_20180904_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='object_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objecting_activities', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='activity',
            name='object_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='related_object_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_objecting_activities', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='activity',
            name='related_object_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='target_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeting_activities', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='activity',
            name='target_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inboxitem',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='creation_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
