# Generated by Django 2.0.8 on 2018-09-20 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0011_auto_20180910_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delivered', models.BooleanField(default=False)),
                ('last_attempt_date', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('inbox_url', models.URLField(max_length=500)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='federation.Activity')),
            ],
        ),
        migrations.RemoveField(
            model_name='inboxitem',
            name='delivery_attempts',
        ),
        migrations.RemoveField(
            model_name='inboxitem',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='inboxitem',
            name='last_delivery_date',
        ),
    ]
