# Generated by Django 2.0.9 on 2018-12-27 16:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import funkwhale_api.federation.models


class Migration(migrations.Migration):

    dependencies = [("federation", "0015_populate_domains")]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="nodeinfo",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=funkwhale_api.federation.models.empty_dict, max_length=50000
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="nodeinfo_fetch_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
