# Generated by Django 2.1.5 on 2019-01-30 09:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import funkwhale_api.common.validators
import funkwhale_api.federation.models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0016_auto_20181227_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='old_domain',
        ),
        migrations.AddField(
            model_name='domain',
            name='service_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_domains', to='federation.Actor'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, validators=[funkwhale_api.common.validators.DomainValidator()]),
        ),
        migrations.AlterField(
            model_name='domain',
            name='nodeinfo',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=funkwhale_api.federation.models.empty_dict, max_length=50000),
        ),
    ]
