# Generated by Django 2.2.2 on 2019-06-11 08:51

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import funkwhale_api.federation.models


class Migration(migrations.Migration):

    dependencies = [("federation", "0018_fetch")]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="allowed",
            field=models.BooleanField(default=None, null=True),
        )
    ]
