# Generated by Django 2.2.6 on 2019-10-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0020_auto_20190730_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Account'},
        ),
        migrations.AlterField(
            model_name='actor',
            name='type',
            field=models.CharField(choices=[('Person', 'Person'), ('Tombstone', 'Tombstone'), ('Application', 'Application'), ('Group', 'Group'), ('Organization', 'Organization'), ('Service', 'Service')], default='Person', max_length=25),
        ),
    ]
