# Generated by Django 2.2.7 on 2019-12-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0021_auto_20191029_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='inbox_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='outbox_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
