# Generated by Django 3.0.4 on 2020-03-17 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('federation', '0024_actor_attachment_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='object_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objecting_activities', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='related_object_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_objecting_activities', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='related_object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeting_activities', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='target_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
